SDK=SDK
INCLUDES=-I. -I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets

# platform independent defines
DEFINES=-DSPNG_STATIC

SOURCES_CPP=airport.cpp coast.cpp collect_airports.cpp depth_map.cpp log_msg.cpp sub_exec.cpp \
    grib.cpp create_snow_png.cpp xa-snow.cpp
SOURCES_C= spng.c http_get.c

# the c++ standard to use
CXXSTD=-std=c++20

OPT=-O3

# e.g. -DNDEBUG
DEBUG=

